spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql.username}
    password: ${mysql.password}

mysql:
  host:
  port:
  database: simple_blog_api
  username:
  password:

jwt:
  secret: secret
  # 1 day
  expiration: 86400000